export const styles = {
  container: `min-h-screen bg-gray-50 dark:bg-gray-900 font-sans text-gray-900 dark:text-gray-100`,
  header: `bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 px-6 py-8`,
  headerContent: `max-w-5xl mx-auto`,
  title: `text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-3`,
  description: `text-gray-600 dark:text-gray-400 mt-2`,
  main: `max-w-5xl mx-auto px-6 py-8`,
  grid: `grid grid-cols-1 lg:grid-cols-3 gap-6`,
  leftColumn: `lg:col-span-2 space-y-6`,
  rightColumn: `space-y-6`,
  card: `bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 overflow-hidden`,
  cardHeader: `px-5 py-4 border-b border-gray-200 dark:border-gray-700`,
  cardTitle: `text-lg font-semibold text-gray-900 dark:text-white`,
  cardDescription: `text-sm text-gray-500 dark:text-gray-400 mt-1`,
  cardContent: `px-5 py-4 space-y-4`,
  formGroup: `space-y-2`,
  label: `block text-sm font-medium text-gray-700 dark:text-gray-300`,
  input: `w-full px-3 py-2 rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors`,
  select: `w-full px-3 py-2 rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors cursor-pointer`,
  colorInput: `w-full h-10 rounded-md border border-gray-300 dark:border-gray-600 cursor-pointer`,
  checkbox: `w-4 h-4 rounded border-gray-300 dark:border-gray-600 text-blue-600 focus:ring-blue-500 cursor-pointer`,
  checkboxLabel: `flex items-center gap-3 cursor-pointer`,
  range: `w-full h-2 rounded-lg appearance-none cursor-pointer bg-gray-200 dark:bg-gray-700`,
  rangeValue: `text-sm text-gray-500 dark:text-gray-400`,
  row: `grid grid-cols-2 gap-4`,
  button: `px-4 py-2 rounded-md font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2`,
  buttonPrimary: `bg-blue-600 text-white hover:bg-blue-700 focus:ring-blue-500`,
  buttonSecondary: `bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600 focus:ring-gray-500`,
  buttonSuccess: `bg-green-600 text-white`,
  actions: `flex items-center justify-between gap-4 mt-6 px-5 py-4 bg-gray-50 dark:bg-gray-800/50 border-t border-gray-200 dark:border-gray-700`,
  badge: `px-2 py-1 text-xs font-medium rounded-full bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400`,
  previewContainer: `relative h-48 bg-gray-100 dark:bg-gray-900 rounded-lg border-2 border-dashed border-gray-300 dark:border-gray-600 overflow-hidden`,
  previewButton: `absolute flex items-center justify-center text-white shadow-lg transition-all`,
  languageSwitch: `flex items-center gap-2 text-sm`,
  languageButton: `px-3 py-1 rounded-md transition-colors`,
  languageActive: `bg-blue-600 text-white`,
  languageInactive: `bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-300 dark:hover:bg-gray-600`,
};
